[build]
  command = "rm -rf node_modules package-lock.json && npm install && npm run build -- --configuration production"
  publish = "dist/messenger-app-front/browser"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_VERSION = "18"